### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mktcode**
Fixed link....

**I also noticed this repository seems to be outdated. The website runs on PHP now and the repository only contains html files. Why is this?**

### CODE REVIEW

**Review by AIR-CLINIC — APPROVED** [review]
Hey @mktcode thank you for the changes you made. We will definitely update it to reflect the Php aspects of the code. We appreciate.

**Comment by mktcode** [comment]
So... don't you want to merge this PR? :>

**Comment by AIR-CLINIC** [comment]
Its done @mktcode. Thank you!
We would love you to get more involved in this project if you are up for it.

**Comment by mktcode** [comment]
I'm afraid there's not enough time to get involved in yet another project. I'm sorry! :(

**Pull request merged**
